### ISSUE TITLE
Headings

### ISSUE THREAD

**Issue by pcha11** [brandaid/dashboard#10]
The headings above the tables are not very useful as they don't stand out in any way (Active Studies, General Screeners, Completed Studies). Can you find a way to make them more useful?

Also, you can drop the "testing dates" and "active dates" labels in that heading row. They could technically go over the dates in the tables below, but just changing those to "begin date" and "end date" would be simpler.

**Comment by jeremymansfield** [comment]
@pcha11 OK, so ...
- Make the **Active Studies**, **General Screeners** and **Completed Studies** headlines larger and bolder, perhaps?
- And delete _Testing Dates_ & _Active Dates_, correct?

**Comment by pcha11** [comment]
Yes, that's right.

**Comment by jeremymansfield** [comment]
@heypaxton Made these edits in the develop branch. Ready for you to merge into master with your other changes.

**Comment by heypaxton** [comment]
These have been merged @jeremymansfield
