### ISSUE TITLE
Table column widths

### ISSUE THREAD

**Issue by pcha11** [brandaid/dashboard#11]
The 3 tables (Active/General/Completed Studies) should have columns consistent between them. The dates and progress fields should have fixed widths and float right, with the name taking up any slack. That way on full screen the columns all line up between the 3 tables, and as the screen shrinks the name field shrinks up to the point where the scroll bar appears.

**Comment by jeremymansfield** [comment]
@heypaxton what's possible for aligning these up equally for desktop when there is no content in the columns at all, but still matching the columns that do have content?

![table-column-alignment](https://cloud.githubusercontent.com/assets/8506396/13959854/d01117ac-f023-11e5-9e22-212d77a359e8.png)

**Comment by heypaxton** [comment]
I had to set a width on the `td` in order to accomplish this.

**Comment by pcha11** [comment]
This looks much better but could be further improved by making all the progress bars line up in each column. Perhaps each <td> should be right-justified, and we should have the alert icon pop up to the left of the fraction rather than to the right of the progress bar.

**Comment by jeremymansfield** [comment]
@heypaxton Is this level of control responsively reasonable?

**Comment by heypaxton** [comment]
The best solution I could find here was to align the last 3 columns to the right. This has all right alignment. Since the text length will vary I put the warning sign behind the text. Take a look and let me know what you think.

**Comment by jeremymansfield** [comment]
I think that will have to work and looks great. Closing this item.

**Comment by pcha11** [comment]
I think it would look better with the alert to the left of the text. While the text varies in length, at least all the text would be aligned on the left margin where it meets the progress bars. The alert is generally not seen so there would be only one uneven edge, which is already uneven anyway due to the different lengths of text.

**Comment by heypaxton** [comment]
This has been updated 717b82e

**Comment by pcha11** [comment]
Looks great -
