### ISSUE TITLE
iOS Content Issue

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#12]
On iOS (I'm on iPhone 6), the content of the page won't scroll. It's just whatever is there is there. When you open up the off-canvas nav, you can then scroll the page down.

**Comment by heypaxton** [comment]
What I see is the table scrolling is highjacking the page scroll. I'll see if there is a way around it.

**Comment by jeremymansfield** [comment]
Just wanted to check in on this.

**Comment by heypaxton** [comment]
@jeremymansfield I did a couple hours research on this over the weekend. It appears it's a bug/feature in IOS with multiple scroll directions. I've tried a few things, none resolving the issue. The scrolling works when you grab outside of the table, but if inside the table the overflow-x: scroll takes over. Perhaps we could increase the padding around the table as one solution. Or, we could make the user tap to initiate interaction with the table, then disable interaction. For instance, opening the table in a modal, then closing the modal.

**Comment by jeremymansfield** [comment]
Ug. I wonder why the original example works on iOS. Simply because this is older code?

**Comment by heypaxton** [comment]
I'm gonna try it in an older version of IOS and see if there is a difference.

**Comment by jeremymansfield** [comment]
Thx. This original example works with current version of iOS: http://zurb.com/playground/projects/responsive-tables/index.html

**Comment by jeremymansfield** [comment]
Issue wasn't even the table. It was the off-canvas-wrapper.

<img width="339" alt="webkit-overflow-scrolling-touch" src="https://cloud.githubusercontent.com/assets/8506396/14114148/8d0ee5e2-f59b-11e5-88bd-a7af9fc54b3c.png">
