### ISSUE TITLE
Style Hover State for Menus

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#15]
@heypaxton, they are looking to add a "hover" state to the left-hand primary and sub-menus when you hover over them. I think having the text and / or text & icon hover transition to the blue color would work well. Thoughts?

**Comment by heypaxton** [comment]
I think that could work. Do you want to change the active state too?

**Comment by jeremymansfield** [comment]
Originally, I think I had intended the hover state on the primary navigation to be the same as the open state. For the secondary navigation, I think a bolder version of the font with the blue as a highlight will work well. Thoughts?

![hover-primary](https://cloud.githubusercontent.com/assets/8506396/15291330/e96bf380-1b42-11e6-907a-b233d115db61.png)
![hover-secondary](https://cloud.githubusercontent.com/assets/8506396/15291333/eb377a36-1b42-11e6-9825-554039b5f3e0.png)

**Comment by heypaxton** [comment]
Ok I see what you mean.

**Comment by jeremymansfield** [comment]
@pcha11 Peter, the rollover has been implemented for the front-end.
http://www.insightcounts.com.php56-2.ord1-1.websitetestlink.com

**Comment by pcha11** [comment]
Thank you - looks good
