### ISSUE TITLE
Avatar dropdown

### ISSUE THREAD

**Issue by pcha11** [brandaid/dashboard#16]
I realized the avatar dropdown list items are not responding to hover etc. What did you have in mind for that?

**Comment by jeremymansfield** [comment]
Not fully sure I understand. The Avatar dropdown has always been a click event and not hover.

**Comment by pcha11** [comment]
Well, you click to make it drop down, but then it seems like if you're postioned over Account Settings or Support or Log Out there should be some indication that you're over them and that they're clickable. It actually looks like there is a hover state defined in the css but nothing's happening on the page.

**Comment by jeremymansfield** [comment]
@heypaxton can you see about adding a hover state to the Avatar dropdown list. I think just having each of the words transition to the darker font color will work.

![screen shot 2016-06-01 at 3 37 43 pm](https://cloud.githubusercontent.com/assets/8506396/15724937/11a14cfa-280f-11e6-90ad-11a2d58a30e0.png)

**Comment by heypaxton** [comment]
@jeremymansfield this has been added. Remind me again. Should "My Profile" have any hover action?

**Comment by jeremymansfield** [comment]
@pcha11 Do you desire that "My Profile" have any hover action? I don't forsee it having the hover since it's the active / directional state of what the dropdown is about.

**Comment by pcha11** [comment]
I agree
