### ISSUE TITLE
Icon Sizes

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#17]
@heypaxton @pcha11 Circling us all up regarding a question Peter had with smaller icons displaying next to each other in tables.

Per @pcha11, On many tables they are having a sizing / proportion issue with the edit and delete icon using the [Glyphicons](http://glyphicons.com) E151 and E017. Should there be, or is there already, something in the stylesheet that specifies how big those are, how much space is between them, etc.? Their developer has put them on the page but they feel they are too close together and too small, and they are thinking there should be a standard enforced through the css.

![image001](https://cloud.githubusercontent.com/assets/8506396/15751617/58a5acf8-28b0-11e6-858c-c6418e9aa14c.png)

@pcha11 We've already sort of established sizes of icons with the yellow caution icon shown / displayed inline with the tables as seen on our staging site > http://www.insightcounts.com.php56-2.ord1-1.websitetestlink.com  ... I'm going to estimate keeping them around that size is a good balance on scaling and spacing.

Thoughts?

**Comment by pcha11** [comment]
I think we're good. I realized that the icons shown above aren't glyphicons. Changing that and fixing the class made them appear larger and more spaced out.
