### ISSUE TITLE
Logo / Title Bar Fix

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#2]
Can we get the client logo (P&G example) to float left over the menu bar and can we get the case# and Client Name to float right over the avatar? https://invis.io/C26I7AYM8

**Comment by heypaxton** [comment]
This is fixed by removing the `row` from inside the `topbar`. Assigning for review.

**Comment by jeremymansfield** [comment]
Can we get this closer to the default Foundation off-canvas functionality where the logo is part of the entire left column? As is, the off-canvas is buggy and disappears when re-orienting a device and expanding / contracting in the browser. https://github.com/brandaid/dashboard/issues/3

![screen shot 2016-03-17 at 9 17 25 am](https://cloud.githubusercontent.com/assets/8506396/13848722/1be9cb80-ec21-11e5-9f02-7e6a4e7be64b.png)

**Comment by heypaxton** [comment]
This has been moved to rely completely on foundation and uses the top bar in the off canvas nav. This should be addressed in #6.

**Comment by jeremymansfield** [comment]
Looks like the left-hand nav doesn't extend all the way down the page like originally intended. Might have the colors reversed on functionality? Check out the InVision flow > https://invis.io/C26I7AYM8

Also, if there was a minor issue in Foundation 5 with the background of the off-canvas nav not going 100% vertical and simply cutting off with the content. I found the fix for that on this StackOverflow thread > http://stackoverflow.com/questions/20484240/100-height-off-canvas-foundation-5/20941659#20941659
