### ISSUE TITLE
Menu expand / collapse

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#3]
If I remember correctly, you had the menu expansion working on the Style Guide, but it looks like it doesn’t work anymore. Can you enable that functionality so the client can roll with it from there?

**Comment by jeremymansfield** [comment]
Looks to be working. Closing this issue for now.

**Comment by jeremymansfield** [comment]
The left-menu is not expanding and collapsing anymore. Can you test on your end?

**Comment by heypaxton** [comment]
I broke it while toying with something else. c6fd6c4 should fix it.
