### ISSUE TITLE
Mobile Table Scrolling

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#5]
It looks like the table is not scrolling on smaller screen sizes when it is collapsed. I didn't realize Foundation 6 doesn't do this out of the box. My sincere apologies. I was remembering doing this functionality from this Foundation resource: http://zurb.com/playground/responsive-tables

**Comment by heypaxton** [comment]
I interpreted this incorrectly. I've add the scroll behavior. It's done by just adding `scroll` class to the table. Assigning for review.

**Comment by jeremymansfield** [comment]
Close. However, the intent would be for the left column to be viewable at all times and the other content to scroll underneath it. Check out how it works on this link > http://zurb.com/playground/projects/responsive-tables/index.html

Also, the table lost it's full width.
![table-full-width](https://cloud.githubusercontent.com/assets/8506396/13848674/e7c2a61a-ec20-11e5-956d-1a68abcb9a25.png)

**Comment by heypaxton** [comment]
Tables are back to full width now, but looks like the rows are off after adding the plugin so i'll work on a fix for that.

**Comment by jeremymansfield** [comment]
Can you reference the GitHub link with the Edge update here for us to archive and keep up with?

**Comment by heypaxton** [comment]
This is the patch https://github.com/NicholasRBowers/responsive-tables/commit/cfe0ab897ac61a107baa51d2bcb0333f4bf6c0c8
