### ISSUE TITLE
Off-Canvas Navigation

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#6]
I noticed a bug on the off-canvas mobile navigation. When you expand it and collapse it and then re-orient the screen, the navigation disappears. This happens on desktop and on mobile. 

What were the challenges of purely using the off-canvas treatment like Foundation has? I noticed it’s not quite the same experience and a little awkward when I am on desktop and shrinking the screen down to get it to switch to mobile view. The off-canvas navigation sort of peeks out at times. Is it possible to achieve what I created in my layouts using Foundation?

For any mobile landscape view, let’s let it go to the mobile navigation switch with the off-canvas so everything doesn’t squish.

![img_5689](https://cloud.githubusercontent.com/assets/8506396/13811708/8ca2d830-eb45-11e5-9521-90d6d942b51b.png)

![img_5690](https://cloud.githubusercontent.com/assets/8506396/13811710/8f8444da-eb45-11e5-828a-33b9d44be437.png)

**Comment by pcha11** [comment]
the menu also goes missing if you shrink the screen down to a mobile size on the desktop & then enlarge it again - no orientation change needed. Refresh is required to bring it back.

**Comment by heypaxton** [comment]
- [ ] Fix larger phone/tablet columns
- [ ] Enter toggle view for tablet size

**Comment by jeremymansfield** [comment]
@heypaxton I'm thinking you've "fixed larger phone / tablet columns" and "enter toggle view for tablet size" on your list above? Closing for right now. Re-open if that's not the case.
