### ISSUE TITLE
Alert Modal

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#7]
Please include the alert modal on hover.

![screen shot 2016-03-16 at 11 04 43 am](https://cloud.githubusercontent.com/assets/8506396/13819285/ffac4b74-eb66-11e5-9b60-c9fb4229d2fd.png)

**Comment by heypaxton** [comment]
This should still be an open issue FYI

**Comment by heypaxton** [comment]
This is fixed @jeremymansfield

**Comment by jeremymansfield** [comment]
Looks great. Closing.
