### ISSUE TITLE
Desktop Sidebar Navigation

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#8]
Just need to reverse the desktop nav bar backgrounds and extend to 100% height.

![desktop-dashboard-fixes](https://cloud.githubusercontent.com/assets/8506396/13881756/2cc3353e-ecf0-11e5-91ed-25254a4ea5fb.png)

**Comment by jeremymansfield** [comment]
Looking great so far with color inversion. I'm only still seeing the navigation not extending 100% vertically on larger screen sizes.

**Comment by heypaxton** [comment]
@jeremymansfield This now should look like the image below as tested on iOS. Let me know if you are still seeing different.

![simulator screen shot mar 21 2016 8 58 28 am](https://cloud.githubusercontent.com/assets/543800/13940072/8984d58a-ef97-11e5-8722-b75016616af8.png)

**Comment by jeremymansfield** [comment]
Looking good, sir!

**Comment by jeremymansfield** [comment]
Can you verify the left-hand dashboard navigation background is extending full height on large monitors. On my 27" I am still seeing it cut off in Safari, FireFox and Chrome after multiple restarts and clearing cache and cookies.

![dashboard-desktop-nav](https://cloud.githubusercontent.com/assets/8506396/13956352/69e45348-f016-11e5-9e04-77cb84980ec5.png)

**Comment by heypaxton** [comment]
Having trouble replicating this one, but I'll keep looking. Here's the a screenshot from Safari 9.0.3. Top and bottom of window. I duplicated the table in the markup to make the content longer just to be sure. 
![screen shot 2016-03-22 at 8 36 04 am](https://cloud.githubusercontent.com/assets/543800/13957333/59cd2c44-f009-11e5-8833-9c6bf2f6e6e9.png)
![screen shot 2016-03-22 at 8 36 09 am](https://cloud.githubusercontent.com/assets/543800/13957337/5d249328-f009-11e5-8adb-cd10d01c8782.png)

**Comment by jeremymansfield** [comment]
It's actually if your browser / screen is longer than the content. If the content doesn't fill the screen, the left-nav doesn't fill it either. t'm on Safari 9.1, Chrome 49.0.2623.87 and FireFox 45.0.1.Strange. Not sure how to clear it out.

![screen shot 2016-03-22 at 11 44 22 am](https://cloud.githubusercontent.com/assets/8506396/13959777/72539ef0-f023-11e5-8e64-27ff9a0747b5.png)

**Comment by heypaxton** [comment]
I found the issue on this one. It should be fixed now. Thanks for helping troubleshoot.
