### ISSUE TITLE
Dropdowns

### ISSUE THREAD

**Issue by jeremymansfield** [brandaid/dashboard#9]
You can use the same style for the New Study and Filter dropdowns that we are using for the Avatar dropdown.

![screen shot 2016-03-18 at 11 17 44 am](https://cloud.githubusercontent.com/assets/8506396/13884231/21681104-ecfb-11e5-8df8-a4d1d6ac11df.png)

**Comment by pcha11** [comment]
Good point, Jeremy. I had wondered why they looked odd and out of place. That formatting will help.

**Comment by jeremymansfield** [comment]
Looking great. I would only suggest having the feint gray line separating each list item in the dropdown, similar to the feint gray line separating each list in the avatar account dropdown.

**Comment by pcha11** [comment]
The dropdown for the avatar has a small triangle pointing up to it which would be helpful on the other two dropdowns as well. Otherwise they seem to float in a disjointed way and aren't clearly related to the item above them.

**Comment by jeremymansfield** [comment]
Looks good. Closing.

**Comment by pcha11** [comment]
The dropdowns for filter and new study appear when you hover over the menu item, but the one for the avatar only appears if you click the down arrow. It seems they should be consistent. I'm more inclined toward clicking than hovering I think, but I don't feel too strongly either way.

**Comment by jeremymansfield** [comment]
@heypaxton can we enable the filter and new study dropdowns on click instead of on hover?

**Comment by jeremymansfield** [comment]
@heypaxton noticed a bug when I click directly on the "New Study" or "Filter" link. The entire blue header bar disappears on me and I have to refresh the page to get it back. Hopefully switching the functionality to a click event vs. hover will correct the issue?

**Comment by heypaxton** [comment]
This is a mystery. I ran it through a validator to make sure the markup was [valid](https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fwww.insightcounts.com.php56-2.ord1-1.websitetestlink.com%2F). After commenting our some functions, I determined that it's coming from foundation. Looking into it.

**Comment by jeremymansfield** [comment]
I'd try to switch the function to be on click like the avatar/user dropdown first and see if that takes care of it if you can.

**Comment by heypaxton** [comment]
This should be working now @jeremymansfield
